name: Cleanup

on:
  schedule:
    - cron: '50 20 * * 2'  

jobs:
  conditional-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional cleanup at 4 AM CST
        run: |
          timestamp=$(date +%s)
          hour_cst=$(TZ=Asia/Shanghai date +%H)

          echo "当前北京时间小时数：$hour_cst"

          if [ "$hour_cst" = "04" ]; then
            echo "当前为凌晨 4 点，开始执行清理请求..."
            response=$(curl -s "https://tc.qdqqd.com/cleanupwc?time=$timestamp")
            echo "清理接口响应：$response"
          else
            echo "非凌晨 4 点，跳过清理请求。"
          fi
