name: Scheduled Requests

on:
  schedule:
    - cron: '*/2 * * * *' # 每隔 2 分钟触发一次，可根据需求自行调整

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make HTTP requests
        run: |
          curl https://qdqqd.com/qdqqd
          curl https://purge.jsdelivr.net/gh/qdqqd/Url-Shorten-Worker/index.html
          curl https://purge.jsdelivr.net/gh/qdqqd/Url-Shorten-Worker@main/index.html
          curl https://qdqqd.com/
