name: Scheduled Requests

on:
  schedule:
    - cron: '*/1 * * * *' # 每隔 2 分钟触发一次，可根据需求自行调整

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make HTTP requests
        run: |
          curl https://www.google.com/url?sa=t&rct=j&q=柯艺云&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiKq_qR15SAAxUjbfUHHc5PBfIQFnoECBkQAQ&url=https%3A%2F%2Fwww.qdqqd.com%2F&usg=AOvVaw1Q5rfvekYu3ENZQRBgxm6g&opi=89978449
          curl https://qdqqd.com/
          curl https://www.baidu.com/link?url=k6MpuxpsfWu1q3XbJqMf31xdnRFZlPLI0XofqdrtMtG&wd=柯艺云&eqid=c138d464000f60670000000564b37e14
          curl https://www.baidu.com/link?url=eI3xWiks2lvVhUQD2SghshXfGu4ArJbOF_3x_kGsjKW&wd=柯艺云&eqid=94451128000264490000000564b0ceb6
          curl https://www.qdqqd.com/
          curl https://s.qdqqd.com/
          curl https://tc.qdqqd.com/
          curl https://dwz.qdqqd.com/
